### ISSUE TITLE
Train Time

### ISSUE THREAD

**Issue by WuYufeng98** [wonjongg/StyleCariGAN#15]
According to the configuration in your paper, how long does it take to train by default? emmmm, can the 24g 3090 be trained?

**Comment by wonjongg** [comment]
As mentioned in the paper, the training time with 4 NVIDIA Quadro RTX 8000 (48 GB) GPUs was about 8 hours. If you want to get more exaggeration effects, training longer will be helpful. Otherwise, please early stop the training. I'm not sure that the 24GB GPU can be used to train our network. But, just in my opinion, it will be enough.
