### ISSUE TITLE
Number of images generated

### ISSUE THREAD

**Issue by chenxwh** [wonjongg/StyleCariGAN#5]
Hi I have tried the model, really cool! 
Just wondering whether it always generate 64 images? is there a way to output the 'best one'/ 'best ones'? 
Or do the 64 output from the style palette have style names if I just want to have one of a few output?

Thank you

**Comment by wonjongg** [comment]
Hi,
You can generate countless examples by sampling style code from Gaussian distribution. Maybe you can use torch.randn() for random sampling. 

Since everyone has different personal preferences, it is really difficult to define which output or style is 'best'. Our current work does not suggest methods to find the best caricature output. I think it will be a good future work.

If you want to have one of a few output, you should put the style code (.pt) in the same directory with your image file and name the style code as (filename)_style.pt. For more details, please see our test code on sample images.

Thank you for your interest in our work! 😄
